# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Machine-Learning',
                'doc_host': 'https://nextrick.github.io',
                'git_url': 'https://github.com/nextrick/Machine-Learning',
                'lib_path': 'Machine_Learning'},
  'syms': {'Machine_Learning.core': {'Machine_Learning.core.foo': ('core.html#foo', 'Machine_Learning/core.py')}}}
